// <auto-generated />
using BulkyBook.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBookDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250626172458_addForeignKeyForCategoryProductRelation")]
    partial class addForeignKeyForCategoryProductRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyBook.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Scifi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Andrew Hunt & David Thomas",
                            CategoryId = 1,
                            Description = "Classic book on software engineering and best practices.",
                            ISBN = "978-0201616224",
                            ListPrice = 59.990000000000002,
                            Price = 54.990000000000002,
                            Price100 = 44.990000000000002,
                            Price50 = 49.990000000000002,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Martin Fowler",
                            CategoryId = 1,
                            Description = "Improving the design of existing code.",
                            ISBN = "978-0134757599",
                            ListPrice = 69.989999999999995,
                            Price = 64.989999999999995,
                            Price100 = 54.990000000000002,
                            Price50 = 59.990000000000002,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Kyle Simpson",
                            CategoryId = 1,
                            Description = "A deep dive into JavaScript for serious learners.",
                            ISBN = "978-1091210090",
                            ListPrice = 45.0,
                            Price = 40.0,
                            Price100 = 34.0,
                            Price50 = 37.0,
                            Title = "You Don't Know JS Yet"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Thomas H. Cormen",
                            CategoryId = 2,
                            Description = "Comprehensive textbook on algorithms.",
                            ISBN = "978-0262033848",
                            ListPrice = 89.989999999999995,
                            Price = 79.989999999999995,
                            Price100 = 69.989999999999995,
                            Price50 = 74.989999999999995,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Robert C. Martin",
                            CategoryId = 7,
                            Description = "A guide to building maintainable and scalable software systems.",
                            ISBN = "978-0134494166",
                            ListPrice = 65.0,
                            Price = 58.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "Clean Architecture"
                        });
                });

            modelBuilder.Entity("BulkyBook.Models.Product", b =>
                {
                    b.HasOne("BulkyBook.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
